media:
  input: src/img
  output: ../../img
content:
  - name: releases
    label: Releases
    path: src/content/releases
    type: collection
    fields:
      - name: title
        label: Title
        type: string
      - name: link
        label: Link
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Image
        type: image

