media:
  input: src/img
  output: ../../img
content:
  - name: releases
    label: Releases
    path: src/content/releases
    type: collection
    sort: [title]
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: link
        label: Link
        type: string
        required: true
      - name: cover
        label: Image
        type: image
        required: true
